### ISSUE TITLE
bug: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by skramm** [softwaretechnik-berlin/dbml-renderer#30]
Hi,
Seems like a nice tool, unfortunately I am unable to make it work.
I installed it in a Ubuntu 22 docker container, installed npm , dit this:
```
npm install -g @softwaretechnik/dbml-renderer
```
But trying to use it with this `test.dbml` file:
```
Table users {
  id integer
  username varchar
  role varchar
  created_at timestamp
}
```
produces this:

```
# dbml-renderer -i test.dbml -o test.svg
/usr/local/lib/node_modules/@softwaretechnik/dbml-renderer/lib/renderer.js:32
        const tableColor = !this.table.settings?.headercolor
                                                ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@softwaretechnik/dbml-renderer/lib/api.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
Additional info:
```
# npm --version
8.5.1
# nodejs --version
v12.22.9
```
To me, seems that this is a spurious '?', can you confirm (and removed, if so).

**Comment by fleipold** [comment]
Hi @skramm,
Thanks for reporting this issue. '?.' is the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
`node.js` supports it from version 14.

**Comment by skramm** [comment]
Ah. Thanks for info, really not familiar with nodejs. And I was using version 12, that's the one that comes with Ubuntu22 (latest LTS...) that I was running in a container, so I thought it was a bug.
Maybe you could add in the readme that minimum requirement for people like me not familiar with nodejs stuff?
